### ISSUE TITLE
Can anyone help me?

### ISSUE THREAD

**Issue by ardakaraosmanoglu** [LukeProducts/Viewer-2.0#2]
![image](https://user-images.githubusercontent.com/77415587/112198338-0d00dd00-8c1e-11eb-8423-9e158eba11aa.png)

**Comment by LukeProducts** [comment]
Chromedriver has been outdated and will be updated now
Thank you for your report!
warm greetings
LukeProducts

**Comment by LukeProducts** [comment]
now it should work
